name: Create Tag on Push

on:
  push:
    branches:
      - your-target-branch

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"

    - name: Run Bash Script
      run: |
        chmod +x create_tag.sh
        ./create_tag.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
