name: DEV

on:
  push:
    branches:
      - test

jobs:
  create_tag:
    runs-on: ubuntu-latest

    env:
      GITHUB_EMAIL: "${{ github.actor }}@users.noreply.github.com"
      GITHUB_NAME: "${{ github.actor }}"

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --local user.email "${GITHUB_EMAIL}"
        git config --local user.name "${GITHUB_NAME}"

    - name: Get Current Date
      id: date
      run: echo "::set-output name=current_date::$(date +'%Y%m%d')"

    - name: Get Branch Name
      id: branch_name
      run: echo "::set-output name=branch_name::$(echo $GITHUB_REF | awk -F'/' '{print $3}')"

    - name: Get Latest Tag
      id: latest_tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0)
        echo "::set-output name=latest_tag::$latest_tag"

    - name: Extract Version Number
      id: version_number
      run: |
        if [[ "${{ steps.latest_tag.outputs.latest_tag }}" =~ [0-9]+$ ]]; then
            version_number=${{BASH_REMATCH[0]}}
            new_version_number=$((version_number + 1))
        else
            new_version_number=1
        fi
        echo "::set-output name=new_version_number::$new_version_number"

    - name: Create New Tag
      id: new_tag
      run: |
        branch_name="${{ steps.branch_name.outputs.branch_name }}"
        current_date="${{ steps.date.outputs.current_date }}"
        new_version_number="${{ steps.version_number.outputs.new_version_number }}"
        new_tag="$branch_name-$current_date-V1.$new_version_number"
        git tag "$new_tag"
        echo "::set-output name=new_tag::$new_tag"

    - name: Push New Tag
      run: git push origin "${{ steps.new_tag.outputs.new_tag }}"

    - name: Set New Tag as Output
      id: tag_output
      run: echo "::set-output name=tag::$GITHUB_REF"

    - name: Display New Tag
      run: |
        echo "New tag: ${{ steps.tag_output.outputs.tag }}"

    - name: Inform User
      run: echo "Tag \"${{ steps.tag_output.outputs.tag }}\" created successfully!"
